# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build:prod"

# Environment variable injection for client side
[[plugins]]
  package = "@netlify/plugin-inject-env-vars-client-side"

# Headers to set on all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 