name = "royalty-application"
main = "dist/worker.js"
compatibility_date = "2023-10-30"

# Routes for your application
routes = [
  { pattern = "", custom_domain = true }
]

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Environment variables for production
[vars]
# These are placeholder values - do NOT commit actual secrets here
# You will set actual values through Cloudflare dashboard or CLI
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
PAYSTACK_PUBLIC_KEY = ""

# Setting up different environments
[env.production]
# Production-specific settings can go here
workers_dev = false

[env.staging]
name = "royalty-application-staging"
workers_dev = true
# You can define staging-specific values here 